import 'package:flutter/material.dart';
import 'package:satisfactempire/assets.dart';

enum SatisfactoryItem {
  planet('Planète'),
  aucun('Energie'),
  acideNitriqueConditionne('Acide nitrique conditionné'),
  acideNitrique('Acide nitrique'),
  acideSulfurique('Acide sulfurique'),
  acideSulfuriqueConditionne('Acide sulfurique conditionné'),
  azote('Azote'),
  azoteGazeuxConditionne('Azote gazeux contionnné'),
  moteurADistortionBalistique('Moteur à distortion balistique'),
  barreDeCombustibleALUranium('Barre d\'uranium'),
  barreDeFicsonium('Barre de ficsonium'),
  barreDePlutonium('Barre de plutonium'),
  batterie('Batterie'),
  bauxite('Bauxite'),
  bidonVide('Bidon vide'),
  biocarburantLiquide('Biocarburant liquide'),
  biocarburantLiquideConditionne('Biocarburant liquide conditionné'),
  boitierEnAluminium('Boitier en aluminium'),
  beton('Béton'),
  cadreModulaire('Cadre modulaire'),
  cadreModulaireFusionne('Cadre modulaire fusionné'),
  cadreModulaireLourd('Cadre modulaire lourd'),
  calcaire('Calcaire'),
  caoutchouc('Caoutchouc'),
  celluleDUranium('Cellule d\'uranium'),
  celluleDePlutonium('Cellule de plutonium'),
  celluleDeSingularite('Cellule de singularité'),
  charbon('Charbon'),
  charbonCompacte('Charbon compacté'),
  circuitImprime('Circuit imprimé'),
  cokeDePetrole('Coke de pétrole'),
  connecteurHauteVitesse('Connecteur haute vitesse'),
  controleurDIA('Contrôleur d\'IA'),
  cristalDeMatiereNoire('Cristal de matière noire'),
  cristalDeQuartz('Cristal de quartz'),
  cristalTemporel('Cristal temporel'),
  cubeDeConversionDePression('Cube de conversion de pression'),
  cablageAutomatise('Câblage automatisé'),
  cable('Câble'),
  carburant('Carburant'),
  carburantConditionne('Carburant conditionné'),
  dissipateurThermique('Dissipateur thermique'),
  dechetsDUranium('Déchets d\'uranium'),
  dechetsDePlutonium('Déchets de plutonium'),
  diamants('Diamants'),
  eau('Eau'),
  eauConditionnee('Eau conditionnée'),
  emeReanimee('EME réanimée'),
  fluctuateurDEme('Fluctuateur d\'EME'),
  ficsonium('Ficsonium'),
  filElectrique('Fil électrique'),
  filactif('Filactif'),
  filtreAGaz('Filtre à gaz'),
  filtreAInfusionDIode('Filtre à infusion d\'iode'),
  fuseeAPropulsionThermique('Fusée à propulsion thermique'),
  granuleDUranium('Granulé d\'uranium'),
  granuleDePlutonium('Granulé de plutonium'),
  generateurDeChampMagnetique('Générateur de champ magnétique'),
  lingotDAcier('Lingot d\'acier'),
  lingotDAluminium('Lingot d\'aluminium'),
  lingotDeCaterium('Lingo de catérium'),
  lingotDeCuivre('Lingot de cuivre'),
  lingotDeFer('Lingot de Fer'),
  lingotDeFicsite('Lingot de ficsite'),
  matierePhotoniqueAgitee('Matière photonique agitée'),
  mineraiDEME('Lingot d\'EME'),
  mineraiDeCaterium('Minerai de catérium'),
  mineraiDeCuivre('Minerai de cuivre'),
  mineraiDeFer('Minerai de fer'),
  moteur('Moteur'),
  moteurModulaire('Moteur modulaire'),
  moteurTurbo('Moteur turbo'),
  munitionDeFusil('Munition de fusil'),
  munitionDeFusilATeteChercheuse('Munition de fusil à tête chercheuse'),
  munitionDeFusilTurbo('Munition de fusil turbo'),
  nobelisque('Nobélisque'),
  nobelisqueAGaz('Nobélisque à gaz'),
  nobelisqueAImpulsion('Nobélisque à impulsion'),
  nobelisqueAFragmentation('Nobélisque à fragmentation'),
  nobelisqueNucleaire('Nobélisque nucléaire'),
  ordinateur('Ordinateur'),
  ordinateurQuantique('Ordinateur quantique'),
  oscillateurDeSuperposition('Oscillateur de superposition'),
  oscillateurACristal('Oscillateur à cristal'),
  petroleBrut('Pétrole brut'),
  petroleConditionne('Pétrole conditionné'),
  placageIntelligent('Placage intelligent'),
  plaqueDeFer('Plaque de fer'),
  plaqueDeFerRenforcee('Plaque de fer renforcée'),
  plastique('Plastique'),
  poudreDeCuivre('Poudre de cuivre'),
  poudreNoire('Poudre noire'),
  poudreSansFumee('Poudre sans fumée'),
  poutreEnAcier('Poutre en acier'),
  poutreEnBetonArme('Poutre en béton armé'),
  processeurNeuroQuantique('Processeur neuro-quantique'),
  pateNucleaire('Pâte nucléaire'),
  quartzBrut('Quartz brut'),
  rebutsDAluminium('Rebuts d\'aluminium'),
  residussDeMatiereNoire('Résidus de matière noire'),
  residusDePetroleLourd('Résidus de pétrole lourd'),
  rotor('Rotor'),
  reservoirDeFluideVide('Réservoir de fluide vide'),
  residusDePetroleLourdConditionnes('Résidus de pétrole lourd conditionnés'),
  resinePolymere('Résine polymère'),
  serveurDExpansionDIA('Serveur d\'expansion d\'IA'),
  sculptriceBiochimique('Sculptrice biochimique'),
  silice('Silice'),
  solutionDAlumine('Solution d\'alumine'),
  solutionDAlumineConditionnee('Solution d\'alumine conditionnée'),
  soufre('Soufre'),
  stator('Stator'),
  structurePolyvalente('Structure polyvalente'),
  superordinateur('Superordinateur'),
  systemeDeDirecteurDAssemblage('Système de directeur d\'assemblage'),
  systemeDeRefroidissement('Système de refroidissement'),
  tigeDeControleElectromagnetique('Tige de contrôle électromagnétique'),
  tigeDeFer('Tige de fer'),
  tissu('Tissu'),
  turbocarburant('Turbocarburant'),
  turbocarburantConditionne('Turbocarburant conditionné'),
  tuyauEnAcier('Tuyau en acier'),
  toleDaluminiumEnAlliageAlclad('Tôle d\'aluminium en alliage Alclad'),
  toleDeCuivre('Tôle de cuivre'),
  trigonEnFicsite('Trigon en ficsite'),
  uniteDeControleAdaptative('Unité de contrôle adaptative'),
  uniteDeControleRadio('Unité de contrôle radio'),
  uranium('Uranium'),
  uraniumNonFissile('Uranium non fissile'),
  vis('Vis');

  final String name;

  const SatisfactoryItem(this.name);

  AssetImage get image {
    return switch (this) {
      SatisfactoryItem.planet => Images.planet,
      SatisfactoryItem.aucun => Images.powerLine,
      SatisfactoryItem.acideNitriqueConditionne => Images.packagedNitricAcid,
      SatisfactoryItem.acideNitrique => Images.nitricAcid,
      SatisfactoryItem.acideSulfurique => Images.sulfuricAcid,
      SatisfactoryItem.acideSulfuriqueConditionne =>
        Images.packagedSulfuricAcid,
      SatisfactoryItem.azote => Images.nitrogenGas,
      SatisfactoryItem.azoteGazeuxConditionne => Images.packagedNitrogenGas,
      SatisfactoryItem.barreDeCombustibleALUranium => Images.uraniumFuelRod,
      SatisfactoryItem.barreDePlutonium => Images.plutoniumFuelRod,
      SatisfactoryItem.batterie => Images.battery,
      SatisfactoryItem.bauxite => Images.bauxite,
      SatisfactoryItem.bidonVide => Images.emptyCanister,
      SatisfactoryItem.biocarburantLiquide => Images.liquidBiofuel,
      SatisfactoryItem.biocarburantLiquideConditionne =>
        Images.packagedLiquidBiofuel,
      SatisfactoryItem.boitierEnAluminium => Images.aluminumCasing,
      SatisfactoryItem.beton => Images.concrete,
      SatisfactoryItem.cadreModulaire => Images.modularFrame,
      SatisfactoryItem.cadreModulaireFusionne => Images.fusedModularFrame,
      SatisfactoryItem.cadreModulaireLourd => Images.heavyModularFrame,
      SatisfactoryItem.calcaire => Images.limestone,
      SatisfactoryItem.caoutchouc => Images.rubber,
      SatisfactoryItem.celluleDUranium => Images.encasedUraniumCell,
      SatisfactoryItem.celluleDePlutonium => Images.encasedPlutoniumCell,
      SatisfactoryItem.charbon => Images.coal,
      SatisfactoryItem.charbonCompacte => Images.compactedCoal,
      SatisfactoryItem.circuitImprime => Images.circuitBoard,
      SatisfactoryItem.cokeDePetrole => Images.petroleumCoke,
      SatisfactoryItem.connecteurHauteVitesse => Images.highSpeedConnector,
      SatisfactoryItem.controleurDIA => Images.aILimiter,
      SatisfactoryItem.cristalDeQuartz => Images.quartzCrystal,
      SatisfactoryItem.cubeDeConversionDePression =>
        Images.pressureConversionCube,
      SatisfactoryItem.cablageAutomatise => Images.automatedWiring,
      SatisfactoryItem.cable => Images.cable,
      SatisfactoryItem.carburant => Images.fuel,
      SatisfactoryItem.carburantConditionne => Images.packagedFuel,
      SatisfactoryItem.dissipateurThermique => Images.heatSink,
      SatisfactoryItem.dechetsDUranium => Images.uraniumWaste,
      SatisfactoryItem.dechetsDePlutonium => Images.plutoniumWaste,
      SatisfactoryItem.eau => Images.water,
      SatisfactoryItem.eauConditionnee => Images.packagedWater,
      SatisfactoryItem.filElectrique => Images.wire,
      SatisfactoryItem.filactif => Images.quickwire,
      SatisfactoryItem.filtreAGaz => Images.gasFilter,
      SatisfactoryItem.filtreAInfusionDIode => Images.iodineInfusedFilter,
      SatisfactoryItem.fuseeAPropulsionThermique =>
        Images.thermalPropulsionRocket,
      SatisfactoryItem.granuleDUranium => Images.uraniumPellet,
      SatisfactoryItem.granuleDePlutonium => Images.plutoniumPellet,
      SatisfactoryItem.generateurDeChampMagnetique =>
        Images.magneticFieldGenerator,
      SatisfactoryItem.lingotDAcier => Images.steelIngot,
      SatisfactoryItem.lingotDAluminium => Images.aluminumIngot,
      SatisfactoryItem.lingotDeCaterium => Images.cateriumIngot,
      SatisfactoryItem.lingotDeCuivre => Images.copperIngot,
      SatisfactoryItem.lingotDeFer => Images.ironIngot,
      SatisfactoryItem.mineraiDEME => Images.sam,
      SatisfactoryItem.mineraiDeCaterium => Images.cateriumOre,
      SatisfactoryItem.mineraiDeCuivre => Images.copperOre,
      SatisfactoryItem.mineraiDeFer => Images.ironOre,
      SatisfactoryItem.moteur => Images.motor,
      SatisfactoryItem.moteurModulaire => Images.modularEngine,
      SatisfactoryItem.moteurTurbo => Images.turboMotor,
      SatisfactoryItem.ordinateur => Images.computer,
      SatisfactoryItem.ordinateurQuantique => Images.quantumComputer,
      SatisfactoryItem.oscillateurDeSuperposition =>
        Images.superpositionOscillator,
      SatisfactoryItem.oscillateurACristal => Images.crystalOscillator,
      SatisfactoryItem.petroleBrut => Images.crudeOil,
      SatisfactoryItem.petroleConditionne => Images.packagedOil,
      SatisfactoryItem.placageIntelligent => Images.smartPlating,
      SatisfactoryItem.plaqueDeFer => Images.ironPlate,
      SatisfactoryItem.plaqueDeFerRenforcee => Images.reinforcedIronPlate,
      SatisfactoryItem.plastique => Images.plastic,
      SatisfactoryItem.poudreDeCuivre => Images.copperPowder,
      SatisfactoryItem.poudreNoire => Images.blackPowder,
      SatisfactoryItem.poudreSansFumee => Images.smokelessPowder,
      SatisfactoryItem.poutreEnAcier => Images.steelBeam,
      SatisfactoryItem.poutreEnBetonArme => Images.encasedIndustrialBeam,
      SatisfactoryItem.pateNucleaire => Images.nuclearPasta,
      SatisfactoryItem.quartzBrut => Images.rawQuartz,
      SatisfactoryItem.rebutsDAluminium => Images.aluminumScrap,
      SatisfactoryItem.residusDePetroleLourd => Images.heavyOilResidue,
      SatisfactoryItem.rotor => Images.rotor,
      SatisfactoryItem.reservoirDeFluideVide => Images.emptyFluidTank,
      SatisfactoryItem.residusDePetroleLourdConditionnes =>
        Images.packagedHeavyOilResidue,
      SatisfactoryItem.resinePolymere => Images.polymerResin,
      SatisfactoryItem.silice => Images.silica,
      SatisfactoryItem.solutionDAlumine => Images.aluminaSolution,
      SatisfactoryItem.solutionDAlumineConditionnee =>
        Images.packagedAluminaSolution,
      SatisfactoryItem.soufre => Images.sulfur,
      SatisfactoryItem.stator => Images.stator,
      SatisfactoryItem.structurePolyvalente => Images.versatileFramework,
      SatisfactoryItem.superordinateur => Images.supercomputer,
      SatisfactoryItem.systemeDeDirecteurDAssemblage =>
        Images.assemblyDirectorSystem,
      SatisfactoryItem.systemeDeRefroidissement => Images.coolingSystem,
      SatisfactoryItem.tigeDeControleElectromagnetique =>
        Images.electromagneticControlRod,
      SatisfactoryItem.tigeDeFer => Images.ironRod,
      SatisfactoryItem.tissu => Images.fabric,
      SatisfactoryItem.turbocarburant => Images.turbofuel,
      SatisfactoryItem.turbocarburantConditionne => Images.packagedTurbofuel,
      SatisfactoryItem.tuyauEnAcier => Images.steelPipe,
      SatisfactoryItem.toleDaluminiumEnAlliageAlclad =>
        Images.alcladAluminumSheet,
      SatisfactoryItem.toleDeCuivre => Images.copperSheet,
      SatisfactoryItem.uniteDeControleAdaptative => Images.adaptiveControlUnit,
      SatisfactoryItem.uniteDeControleRadio => Images.radioControlUnit,
      SatisfactoryItem.uranium => Images.uranium,
      SatisfactoryItem.uraniumNonFissile => Images.nonFissileUranium,
      SatisfactoryItem.vis => Images.screw,
      SatisfactoryItem.munitionDeFusil => Images.rifleAmmo,
      SatisfactoryItem.munitionDeFusilATeteChercheuse => Images.homingRifleAmmo,
      SatisfactoryItem.munitionDeFusilTurbo => Images.turboRifleAmmo,
      SatisfactoryItem.nobelisque => Images.nobelisk,
      SatisfactoryItem.nobelisqueAGaz => Images.gasNobelisk,
      SatisfactoryItem.nobelisqueAImpulsion => Images.pulseNobelisk,
      SatisfactoryItem.nobelisqueAFragmentation => Images.clusterNobelisk,
      SatisfactoryItem.nobelisqueNucleaire => Images.nukeNobelisk,
      SatisfactoryItem.moteurADistortionBalistique => Images.ballisticWarpDrive,
      SatisfactoryItem.barreDeFicsonium => Images.ficsoniumFuelRod,
      SatisfactoryItem.celluleDeSingularite => Images.singularityCell,
      SatisfactoryItem.cristalDeMatiereNoire => Images.darkMatterCrystal,
      SatisfactoryItem.cristalTemporel => Images.timeCrystal,
      SatisfactoryItem.diamants => Images.diamonds,
      SatisfactoryItem.ficsonium =>Images.ficsonium,
      SatisfactoryItem.lingotDeFicsite => Images.ficsiteIngot,
      SatisfactoryItem.matierePhotoniqueAgitee => Images.excitedPhotonicMatter,
      SatisfactoryItem.processeurNeuroQuantique => Images.neuralQuantumProcessor,
      SatisfactoryItem.residussDeMatiereNoire => Images.darkMatterResidue,
      SatisfactoryItem.serveurDExpansionDIA => Images.aIExpansionServer,
      SatisfactoryItem.sculptriceBiochimique => Images.biochemicalSculptor,
      SatisfactoryItem.trigonEnFicsite => Images.ficsiteTrigon,
      SatisfactoryItem.emeReanimee => Images.reanimatedSAM,
      SatisfactoryItem.fluctuateurDEme => Images.sAMFluctuator,
    };
  }
}
